export const specilization = [
  {id: 2, title: 'Myjobmag', slug: 'myjobmag'},
  {id: 0, title: 'Joblist', slug: 'joblist'},
  {id: 3, title: 'JobGurus', slug: 'jobgurus'},
  {id: 4, title: 'Jobberman', slug: 'jobberman'},
  {id: 5, title: 'Hotnigerianjobs', slug: 'hotnigerianjobs'},
  {id: 6, title: 'Business Analyst'},
  {id: 7, title: 'Cybersecurity Specialist'},
  {id: 8, title: 'Marketing Manager'},
  {id: 9, title: 'Sales Representative'},
  {id: 10, title: 'Human Resources Specialist'},
  {id: 11, title: 'Financial Analyst'},
  {id: 12, title: 'Project Manager'},
  {id: 13, title: 'Content Writer'},
  {id: 14, title: 'Graphic Designer'},
  {id: 15, title: 'Mechanical Engineer'},
  {id: 16, title: 'Electrical Engineer'},
  {id: 17, title: 'Civil Engineer'},
  {id: 18, title: 'Customer Support Specialist'},
  {id: 19, title: 'Network Administrator'},
  {id: 20, title: 'Database Administrator'},
];

export const SpecializationList = [
  'Accountancy or accounting',
  'Actuarial Science',
  'Architecture',
  'Banking and Finance',
  'Biochemistry',
  'Biomedical Engineering',
  'Botany',
  'Business Administration',
  'Cell Biology and Genetics',
  'chemical engineering',
  'Chemistry',
  'civil engineering',
  'Computer Engineering',
  'Computer Science',
  'Dentistry',
  'economics',
  'Electrical Engineering',
  'Engineering',
  'Entry level',
  'Estate Management',
  'Finance',
  'Geology',
  'Geophysics',
  'Graduate Trainee',
  'Industrial Chemistry',
  'Industrial Relations and Personnel Management',
  'internship',
  'jobs',
  'Law',
  'Mass Communication',
  'myjobmag',
  'Mechanical Engineering',
  'Medical Laboratory Science',
  'Medicine and Surgery',
  'Metallurgical and Material Engineering',
  'Microbiology',
  'Nursing',
  'Petroleum Engineering',
  'Pharmacology',
  'Pharmacy',
  'Physiotherapy',
  'Sociology',
];
