export const specilization = [
  { id: 2, title: "WordPress" },
  { id: 0, title: "blogging" },
  { id: 3, title: "Better%20Blogging" },
  { id: 4, title: "customization" },
  { id: 5, title: "DevOps Engineer" },
  { id: 6, title: "Business Analyst" },
  { id: 7, title: "Cybersecurity Specialist" },
  { id: 8, title: "Marketing Manager" },
  { id: 9, title: "Sales Representative" },
  { id: 10, title: "Human Resources Specialist" },
  { id: 11, title: "Financial Analyst" },
  { id: 12, title: "Project Manager" },
  { id: 13, title: "Content Writer" },
  { id: 14, title: "Graphic Designer" },
  { id: 15, title: "Mechanical Engineer" },
  { id: 16, title: "Electrical Engineer" },
  { id: 17, title: "Civil Engineer" },
  { id: 18, title: "Customer Support Specialist" },
  { id: 19, title: "Network Administrator" },
  { id: 20, title: "Database Administrator" },
];
